version: '2'
services:
    comfortville-app:
        image: comfortville
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://comfortville-mariadb:3306/comfortville
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=comfortville-elasticsearch:9300
        ports:
            - 8080:8080
    comfortville-mariadb:
        extends:
            file: mariadb.yml
            service: comfortville-mariadb
    comfortville-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: comfortville-elasticsearch
